### ISSUE TITLE
GET / HTTPError 500

### ISSUE THREAD

**Issue by crowston** [jhschuster/homebridge-lacrosseweb#8]
My log is filling up with messages like:

[3/24/2023, 9:25:53 AM] [LacrosseWeb] GET / HTTPError 500
[3/24/2023, 9:25:53 AM] [LacrosseWeb] HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-lacrosseweb/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: undefined,
  timings: {
    start: 1679664332856,
    socket: 1679664332856,
    lookup: 1679664332856,
    connect: 1679664332882,
    secureConnect: 1679664332925,
    upload: 1679664332925,
    response: 1679664353639,
    end: 1679664353639,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 26,
      tls: 43,
      request: 0,
      firstByte: 20714,
      download: 0,
      total: 20783
    }
  }
}
[3/24/2023, 9:26:13 AM] [LacrosseWeb] POST /login HTTPError 500
[3/24/2023, 9:26:13 AM] [LacrosseWeb] Login failed. Giving up.

**Comment by jhschuster** [comment]
That's odd. It's not happening to me. This looks like the step where it's going to the website and trying to log in. In my configuration I leave the defaults in place -- specifically, under Advanced Settings, the URL should default to `https://lacrossealertsmobile.com/v1.2`

FWIW, I'm running Node 18.15.0 and Homebridge 1.6.0.

**Comment by crowston** [comment]
I just checked my advanced settings and I had http:// not https://. I changed the setting and it works now. Easy fix (if that was really the problem). Odd that it was working before though. Thanks!

**Comment by jhschuster** [comment]
Who knows? I'm glad it's working again!

**Comment by crowston** [comment]
Spoke too soon: it's happening again. 

[3/25/2023, 10:16:07 AM] [LacrosseWeb] GET / HTTPError 500
[3/25/2023, 10:16:07 AM] [LacrosseWeb] HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-lacrosseweb/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: undefined,
  timings: {
    start: 1679753746936,
    socket: 1679753746936,
    lookup: 1679753746936,
    connect: 1679753746952,
    secureConnect: 1679753746985,
    upload: 1679753746985,
    response: 1679753767500,
    end: 1679753767500,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 16,
      tls: 33,
      request: 0,
      firstByte: 20515,
      download: 0,
      total: 20564
    }
  }
}


I tried stopping and restarting Homebridge and got this error:

[3/25/2023, 10:20:07 AM] [LacrosseWeb] POST /login HTTPError 500
[3/25/2023, 10:20:07 AM] [LacrosseWeb] Login failed. Giving up.
[3/25/2023, 10:20:07 AM] [LacrosseWeb] Malformed config, skipping.
[3/25/2023, 10:20:10 AM] [homebridge-lacrosseweb] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[3/25/2023, 10:20:30 AM] [homebridge-lacrosseweb] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

The first seems to be some problem on the Lacrosse side. I'm not sure what can be done about that. The second seems to be some problem handling the first problem.
